export const mockData = {
  statistics: [
    {
      color: "dark",
      id: "Users",
      icon: "group",
      title: "Users",
      count: 281,
      visible: false,
      percentage: {
        color: "success",
        amount: "+55%",
        label: "than lask week",
      },
    },
    {
      icon: "leaderboard",
      id: "ActiveUsers",
      title: "Active Users",
      count: "2,300",
      visible: false,
      percentage: {
        color: "success",
        amount: "+3%",
        label: "than last month",
      },
    },
    {
      color: "success",
      id: "Sites",
      icon: "cell_tower",
      title: "Sites",
      count: "34k",
      visible: false,
      percentage: {
        color: "success",
        amount: "+1%",
        label: "than yesterday",
      },
    },
    {
      color: "primary",
      id: "Active Sites",
      icon: "cell_tower",
      title: "Active Sites",
      count: "+91",
      visible: false,
      percentage: {
        color: "success",
        amount: "",
        label: "Just updated",
      },
    },
  ],
  charts: {
    chartData: [
      {
        categoryName: "Users Count",
        data: [70, 70, 70, 70, 70, 70, 70, 70, 70, 71, 80, 74],
        name: "Users Count",
        type: "area",
        unit: "Number",
        valueDecimals: 1,
      },
      {
        categoryName: "DL",
        data: [70, 73, 60, 71, 64, 76, 58, 55, 65, 71, 80, 74],
        name: "AVG DL Latency",
        type: "area",
        unit: "Number",
        valueDecimals: 1,
      },
      {
        categoryName: "DL",
        data: [70, 73, 60, 71, 64, 76, 58, 55, 65, 71, 80, 74],
        name: "Total DL Volume",
        type: "area",
        unit: "Number",
        valueDecimals: 1,
      },
      {
        categoryName: "UL",
        data: [70, 73, 60, 71, 64, 76, 58, 55, 65, 71, 80, 74],
        name: "Total UL Volume",
        type: "area",
        unit: "Number",
        valueDecimals: 1,
      },
    ],
    xData: [
      "01-01",
      "01-02",
      "01-03",
      "01-04",
      "01-05",
      "01-06",
      "01-07",
      "12-27",
      "12-28",
      "12-29",
      "12-30",
      "12-31",
    ],
    loading: false,
    error: null,
  },
  gridData: [
    {
      nwfid: "1000000",
      latitude: 47.9982979541504,
      longitude: -124.38262508089106,
      sitetype: "MACRO",
      sect: "2",
      azimuth: "120",
      technology: "4G",
      bandgrp: "SUB1",
      oprband: "13",
      sitename: "TIMB",
    },
    {
      nwfid: "10000001",
      latitude: 48.08738346881355,
      longitude: -123.54931861146864,
      sitetype: "MACRO",
      sect: "2",
      azimuth: "120",
      technology: "4G",
      bandgrp: "SUB1",
      oprband: "13",
      sitename: "TIMB",
    },
  ],
};
